import turtle
import random
import time

turtle.setup(800,600)
t = turtle.Pen()
u = turtle.Pen()
r = turtle.Pen()
l = turtle.Pen()
e = turtle.Pen()

def dance_start():
    t.up()
    t.goto(-360,-250)
    t.left(90)
    t.down()
    u.up()
    u.goto(-180,-250)
    u.left(90)
    u.down()
    r.up()
    r.goto(0,-250)
    r.left(90)
    r.down()
    l.up()
    l.goto(180,-250)
    l.left(90)
    l.down()
    e.up()
    e.goto(360,-250)
    e.left(90)
    e.down()

def set_shape_color():
    t.shape('turtle')
    t.color('red')
    t.speed(1)
    u.shape('turtle')
    u.color('green')
    u.speed(1)
    r.shape('turtle')
    r.color('blue')
    r.speed(1)
    l.shape('turtle')
    l.color('orange')
    l.speed(1)
    e.shape('turtle')
    e.color('purple')
    e.speed(1)

def step1():
    t.speed(9)
    u.speed(9)
    r.speed(9)
    l.speed(9)
    e.speed(9)
    for x in range(1,3):
        t.right(45)
        u.right(45)
        r.right(45)
        l.right(45)
        e.right(45)
        t.left(45)
        u.left(45)
        r.left(45)
        l.left(45)
        e.left(45)
        t.right(45)
        u.right(45)
        r.right(45)
        l.right(45)
        e.right(45)
        t.left(45)
        u.left(45)
        r.left(45)
        l.left(45)
        e.left(45)

def step2():
    t.goto(-30,0)
    u.goto(-15,0)
    r.goto(0,0)
    l.goto(15,0)
    e.goto(30,0)
    t.circle(-30)
    u.circle(-30)
    r.circle(-30)
    l.circle(-30)
    e.circle(-30)
    t.circle(30)
    u.circle(30)
    r.circle(30)
    l.circle(30)
    e.circle(30)

def stepx():
    for x in range(1,5):
        t.forward(50)
        u.forward(50)
        r.forward(50)
        l.forward(50)
        e.forward(50)
        t.right(90)
        u.right(90)
        r.right(90)
        l.right(90)
        e.right(90)
        t.circle(30)
        u.circle(30)
        r.circle(30)
        l.circle(30)
        e.circle(30)

def routine():
    dance_start()
    set_shape_color()
    step1()
    step2()

routine()
